import {
	AlertTriangleIcon as AlertTriangle,
	ArrowRightIcon as ArrowRight,
	CheckIcon as Check,
	ChevronLeftIcon as ChevronLeft,
	ChevronRightIcon as ChevronRight,
	CommandIcon as Command,
	CreditCardIcon as CreditCard,
	FileIcon as File,
	GithubIcon as Github,
	HelpCircleIcon as HelpCircle,
	ImageIcon as Image,
	LaptopIcon as Laptop,
	LayoutDashboardIcon as LayoutDashboard,
	LoaderIcon as Loader,
	LogInIcon as LogIn,
	MoonIcon as Moon,
	MoreVerticalIcon as MoreVertical,
	PlusIcon as Plus,
	SettingsIcon as Settings,
	ShoppingBagIcon as ShoppingBag,
	SunIcon as Sun,
	TrashIcon as Trash,
	TwitterIcon as Twitter,
	UserIcon as User,
	UserSquareIcon as UserCircle,
	EditIcon as UserEdit,
	UserXIcon as UserX,
	XIcon as X,
} from "lucide-react";

export type Icon = React.ComponentType<{
	size?: number;
	color?: string;
	strokeWidth?: number;
}>;

export const Icons = {
	dashboard: LayoutDashboard,
	logo: Command,
	login: LogIn,
	close: X,
	product: ShoppingBag,
	spinner: Loader,
	chevronLeft: ChevronLeft,
	chevronRight: ChevronRight,
	trash: Trash,
	employee: UserX,
	page: File,
	userPen: UserEdit,
	user2: UserCircle,
	media: Image,
	settings: Settings,
	billing: CreditCard,
	ellipsis: MoreVertical,
	add: Plus,
	warning: AlertTriangle,
	user: User,
	arrowRight: ArrowRight,
	help: HelpCircle,
	sun: Sun,
	moon: Moon,
	laptop: Laptop,
	github: Github,
	twitter: Twitter,
	check: Check,
};
